# Generated by Django 3.0.6 on 2020-05-29 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200529_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 29, 5, 52, 32, 293192, tzinfo=utc)),
        ),
    ]
