# Generated by Django 3.0.6 on 2020-06-13 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200529_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 6, 35, 3, 244822, tzinfo=utc)),
        ),
    ]
